version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: ferh/coffee-api-start:coffee-api-init
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:8080"
    networks:
      - webnet
networks:
  webnet:
